### ISSUE TITLE
Error when using DisableDeadBodyMode 3

### ISSUE THREAD

**Issue by Stimayk** [oqyh/cs2-Game-Manager-GoldKingZ#8]
Game Manager (Block/Hide Unnecessaries In Game)" (2.0.5)

```
22:58:18 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Value of '-1' is not valid for 'alpha'. 'alpha' should be greater than or equal to 0 and less than or equal to 255.
   at System.Drawing.Color.<CheckByte>g__ThrowOutOfByteRange|327_0(Int32 v, String n)
   at System.Drawing.Color.FromArgb(Int32 alpha, Int32 red, Int32 green, Int32 blue)
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

```
Need to add a check for zero before minimizing
```
public CounterStrikeSharp.API.Modules.Timers.Timer RemoveDeadBody(CCSPlayerController player)
{
    CounterStrikeSharp.API.Modules.Timers.Timer timer = null!;
    timer = AddTimer(Configs.GetConfigData().Mode3_TimeXSecsDecayDeadBody, () =>
    {
        if (player == null || !player.IsValid || player.PlayerPawn == null || !player.PlayerPawn.IsValid || player.PlayerPawn.Value == null || !player.PlayerPawn.Value.IsValid)
        {
            return;
        }

        if (Globals.PlayerAlpha.ContainsKey(player))
        {
            if (Globals.PlayerAlpha[player] > 0)
            {
                Globals.PlayerAlpha[player]--; 
            }

            if (Globals.PlayerAlpha[player] < 0)
            {
                Server.NextFrame(() =>
                {
                    if (Globals.TimerRemoveDeadBody.ContainsKey(player))
                    {
                        Globals.TimerRemoveDeadBody[player]?.Kill();
                        Globals.TimerRemoveDeadBody[player] = null!;
                        Globals.TimerRemoveDeadBody.Remove(player);
                    }
                    if (Globals.PlayerAlpha.ContainsKey(player))
                    {
                        Globals.PlayerAlpha.Remove(player);
                    }
                });
                return;
            }
            
            Color newColor = Color.FromArgb(Globals.PlayerAlpha[player], 255, 255, 255);
            player.PlayerPawn.Value.Render = newColor;
            Utilities.SetStateChanged(player.PlayerPawn.Value, "CBaseModelEntity", "m_clrRender");
        }
    }, TimerFlags.REPEAT | TimerFlags.STOP_ON_MAPCHANGE);

    return timer;
}
```

That's my guess as to how to solve the problem

**Comment by oqyh** [comment]
> Game Manager (Block/Hide Unnecessaries In Game)" (2.0.5)


thx for report ill check it tomorrow ill do some cleanup

**Comment by oqyh** [comment]
> Game Manager (Block/Hide Unnecessaries In Game)" (2.0.5)

Please Use Game Manager  (2.0.6)
